turn-api:
  server:
    auth-secret: "20!9sip"
    admin:
      user: "admin"
      password: "Admin"

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
    url: jdbc:postgresql://sip.saleschat.tech/turn_server?ssl=true
    username: turn-server
    password: turn-server
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        use_sql_comments: true